### ISSUE TITLE
Exception:  fec_file_id missing, filing:  {'report_type_full':...

### ISSUE THREAD

**Issue by sblack4** [Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor#29]
There are filings (from docquery RSS endpoint) that don't have a `fec_file_id`. This one is from the `FinancialSummaryLoader`

```
[ERROR] Exception: 
fec_file_id missing, filing: 
{'report_type_full': 'JULY QUARTERLY', 'total_independent_expenditures': None, 'is_amended': None, 'sub_id': '1082620200239505386', 'amendment_chain': None, 'means_filed': 'paper', 'previous_file_number': -9672513, 'amendment_version': None, 'debts_owed_to_committee': 0.0, 'amendment_indicator': 'N', 'total_disbursements': 0.0, 'house_personal_funds': None, 'file_number': -9672513, 'cash_on_hand_end_period': 27.84, 'coverage_start_date': '2020-04-01T00:00:00', 'opposition_personal_funds': None, 'document_type': None, 'party': None, 'report_year': 2020, 'primary_general_indicator': 'P', 'pages': 7, 'request_type': None, 'update_date': '2020-08-27T00:53:24', 'committee_type': 'O', 'debts_owed_by_committee': 0.0, 'candidate_id': None, 'total_communication_cost': None, 'html_url': None, 'coverage_end_date': '2020-06-30T00:00:00', 'treasurer_name': None, 'net_donations': None, 'document_description': 'JULY QUARTERLY 2020', 'report_type': 'Q2', 'office': None, 'cycle': 2020, 'total_receipts': 0.0, 'state': None, 'candidate_name': None, 'form_type': 'F3X', 'form_category': 'REPORT', 'fec_file_id': None, 'ending_image_number': '202008260300341520', 'pdf_url': 'http://docquery.fec.gov/pdf/514/202008260300341514/202008260300341514.pdf', 'total_individual_contributions': None, 'cash_on_hand_beginning_period': 27.84, 'document_type_full': None, 'receipt_date': '2020-08-13T00:00:00', 'most_recent_file_number': -9672513, 'committee_id': 'C00706929', 'senate_personal_funds': None, 'most_recent': True, 'committee_name': 'HELP AMERICA VOTE', 'election_year': None, 'csv_url': None, 'beginning_image_number': '202008260300341514'} 
Traceback (most recent call last):
   File "/var/task/src/FinancialSummaryLoader.py", line 253, in lambdaHandler
     upsert_filing(filing)   File "/var/task/src/FinancialSummaryLoader.py", line 164, in upsert_filing
     raise Exception(f'fec_file_id missing, filing: {filing}')

```

They seem to all be `F3X` type filings

**Comment by sblack4** [comment]
> F3X - Joint Fundraising Committee (Unauthorized) 

https://transition.fec.gov/rad/documents/GettingStartedManual-UpdatedDecember2011RL.pdf

**Comment by sblack4** [comment]
>  Amazon Redshift does not enforce unique, primary-key, and foreign-key constraints.

https://docs.aws.amazon.com/redshift/latest/dg/c_best-practices-defining-constraints.html

The database doesn't enforce it so the application uses that key to prevent the accumulation of duplicates. We have no way to enforce that with these `fec_file_id`less records.

Can we relax the need for the PK and find a solution to managing the F3X records?

**Comment by cdaniluk** [comment]
I think that this is a limitation we need to live with. These are edge case reports that aren't true filings and aren't affiliated with a candidate or party.

**Comment by sblack4** [comment]
I'll adjust the logic to skip these. There are two places where that needs to happen: the filing sync and the loaders:

`FilingSync`
https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor/blob/28e046c448f51c809d9455dfe62dd3cce1a6d8fc/src/FilingSync.py#L99

`FecFileLoader` (does f1s, sb, SE filings)
https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor/blob/c8640a8bd91ad2ae119cee7df4aafeee9ced2753/src/FECFileLoader.py#L53-L54

`FinancialSummaryLoader` 
https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor/blob/5da3b36b145fbfc36d0fe4405c430961b3f8da4e/src/FinancialSummaryLoader.py#L163

**Comment by sblack4** [comment]
I've deployed the fix to `FinancialSummaryLoader` but am still seeing errors from the old code:

```

[ERROR] Exception: fec_file_id missing, filing: {'total_independent_expenditures': None, 'request_type': None, 'html_url': None, 'total_receipts': 0.0, 'file_number': -9672374, 'party': None, 'opposition_personal_funds': None, 'election_year': None, 'total_individual_contributions': None, 'cash_on_hand_beginning_period': 3920.0, 'beginning_image_number': '202008240300340003', 'debts_owed_by_committee': 0.0, 'update_date': '2020-08-26T00:55:51', 'coverage_start_date': '2020-04-01T00:00:00', 'cycle': 2020, 'is_amended': None, 'report_year': 2020, 'pdf_url': 'http://docquery.fec.gov/pdf/003/202008240300340003/202008240300340003.pdf', 'treasurer_name': None, 'ending_image_number': '202008240300340009', 'means_filed': 'paper', 'form_type': 'F3X', 'house_personal_funds': None, 'candidate_name': None, 'debts_owed_to_committee': 0.0, 'amendment_indicator': 'N', 'amendment_chain': None, 'most_recent': True, 'committee_id': 'C00449009', 'amendment_version': None, 'document_type': None, 'previous_file_number': -9672374, 'fec_file_id': None, 'total_communication_cost': None, 'pages': 7, 'committee_name': 'HISPANIC LEADERSHIP FUND POLITICAL ACTION COMMITTEE', 'coverage_end_date': '2020-06-30T00:00:00', 'document_description': 'JULY QUARTERLY 2020', 'most_recent_file_number': -9672374, 'primary_general_indicator': 'P', 'document_type_full': None, 'senate_personal_funds': None, 'net_donations': None, 'report_type': 'Q2', 'committee_type': 'N', 'receipt_date': '2020-07-15T00:00:00', 'state': None, 'csv_url': None, 'office': None, 'report_type_full': 'JULY QUARTERLY', 'total_disbursements': 0.0, 'form_category': 'REPORT', 'candidate_id': None, 'sub_id': '1082420200239505056', 'cash_on_hand_end_period': 3920.0}
Traceback (most recent call last):
   File "/var/task/src/FinancialSummaryLoader.py", line 253, in lambdaHandler
     upsert_filing(filing)
   File "/var/task/src/FinancialSummaryLoader.py", line 164, in upsert_filing
     raise Exception(f'fec_file_id missing, filing: {filing}')

```

**Comment by sblack4** [comment]
Redeployed and that's fixed. This error seems to be gone.
