### ISSUE TITLE
FilingUnavailableError: The requested FEC file number (None) is unavailable.

### ISSUE THREAD

**Issue by sblack4** [Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor#31]
From `FECFileLoaderSB` see https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor/blob/28e046c448f51c809d9455dfe62dd3cce1a6d8fc/src/FECFileLoader.py#L79
```
[ERROR] FilingUnavailableError: The requested FEC file number (None) is unavailable. Status code 404. 
Traceback (most recent call last):
   File "/var/task/src/FECFileLoader.py", line 82, in lambdaHandler
     for fec_item in fecfile.iter_http(filing_id, options={'filter_itemizations': [FILING_TYPE]}):
   File "/var/task/fecfile/__init__.py", line 135, in iter_http
     raise FilingUnavailableError({'file_number': file_number, 'status_code': r.status_code})
--
```

**Comment by sblack4** [comment]
This shouldn't be possible. See this file https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor/blob/28e046c448f51c809d9455dfe62dd3cce1a6d8fc/src/FECFileLoader.py#L78

```
        message_parsed = parse_message(message)
        filing_id = deepcopy(message_parsed['filing_id'].replace('FEC-', ''))

        logger.debug(f'filing_id:{filing_id}')
        if not filing_id:
            raise Exception(f'Missing filing ID for filing record {message_parsed}')
```

How are these happening anyway? Is there some weird python lazy evaluation bug or something I'm missing?

**Comment by sblack4** [comment]
The filing_id was the string `None` and so evaluated to `True`. 

These records seem to be all `F3X` records as seen in #29 / `FinancialSummaryLoader`

**Comment by sblack4** [comment]
This has been fixed.
