### ISSUE TITLE
Exception: 404 from https://api.open.fec.gov/v1/committee...

### ISSUE THREAD

**Issue by sblack4** [Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor#32]
```
[ERROR] Exception: 404 from https://api.open.fec.gov/v1/committee/C00685479/totals/?api_key=, response: <Response [404]> 
Traceback (most recent call last):
   File "/var/task/src/FinancialSummaryLoader.py", line 247, in lambdaHandler
     totals = get_totals(committee_id, deepcopy(filters))
   File "/var/task/src/FinancialSummaryLoader.py", line 126, in get_totals
     for report in openFec.get_route_paginator(totals_path, filters):
   File "/var/task/src/OpenFec.py", line 118, in get_route_paginator
     first_response = self.get_route(route, payload)
   File "/var/task/src/OpenFec.py", line 106, in get_route
     response = self._get_request(url, payload)
   File "/var/task/src/OpenFec.py", line 73, in _get_request
     raise Exception(f'404 from {url}, response: {response}')
--
```

**Comment by sblack4** [comment]
Right now this and #30 are the only errors I see. There are two of these type errors thrown in the last 12 hours for IDs
`C00704783` and `C00704858`

**Comment by sblack4** [comment]
When a committee Id is 404 not found do we want to throw an exception so that it's tried again or do we want to log a warning and skip it?

**Comment by sblack4** [comment]
Subsequent calls 

> Right now this and #30 are the only errors I see. There are two of these type errors thrown in the last 12 hours for IDs
> `C00704783` and `C00704858`

subsequent `curl`s for those committees failed with a 404

**Comment by sblack4** [comment]
logging warning and then ignoring committee IDs that give 404s
