### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0) Traceback

### ISSUE THREAD

**Issue by sblack4** [Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor#33]
```
@ingestionTime
1600187636009
@log
648881544937:/aws/lambda/serverless-aws-python3-fec-datasync-dev-FinancialSummaryLoader
@logStream
2020/09/15/[$LATEST]ecec9dba029642df92b60aa30bbcc538
@message
[ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
   File "/var/task/src/FinancialSummaryLoader.py", line 246, in lambdaHandler
     filings = get_filings(deepcopy(filters))
   File "/var/task/src/FinancialSummaryLoader.py", line 104, in get_filings
     for report in openFec.get_route_paginator(path, filters):
   File "/var/task/src/OpenFec.py", line 123, in get_route_paginator
     next_page = self.get_route(route, payload)
   File "/var/task/src/OpenFec.py", line 106, in get_route
     response = self._get_request(url, payload)
   File "/var/task/src/OpenFec.py", line 75, in _get_request
     logger.debug(response.json())
   File "/var/task/requests/models.py", line 898, in json
     return complexjson.loads(self.text, **kwargs)
   File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads
     return _default_decoder.decode(s)
   File "/var/lang/lib/python3.7/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/var/lang/lib/python3.7/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
@timestamp
1600187629495
```

**Comment by sblack4** [comment]
I guess I shouldn't assume it's json 

```
   File "/var/task/src/OpenFec.py", line 75, in _get_request
     logger.debug(response.json())
```

https://github.com/Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor/blob/a3d6b1e9a4057e6544afdeb9ed1005e31a021ae3/src/OpenFec.py#L75

**Comment by sblack4** [comment]
Pushed a commit that should fix this. I haven't been able to repeat this error.

**Comment by sblack4** [comment]
It's still throwing these.

```
@ingestionTime
1600610789865
@log
648881544937:/aws/lambda/serverless-aws-python3-fec-datasync-dev-FinancialSummaryLoader
@logStream
2020/09/20/[$LATEST]ea3e372df06a4449b9d0d9fb9f6bac90
[ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
   File "/var/task/src/FinancialSummaryLoader.py", line 248, in lambdaHandler
     filings = get_filings(deepcopy(filters))
   File "/var/task/src/FinancialSummaryLoader.py", line 104, in get_filings
     for report in openFec.get_route_paginator(path, filters):
   File "/var/task/src/OpenFec.py", line 131, in get_route_paginator
     next_page = self.get_route(route, payload)
   File "/var/task/src/OpenFec.py", line 114, in get_route
     response = self._get_request(url, payload)
   File "/var/task/src/OpenFec.py", line 89, in _get_request
     logger.debug(response.json())
   File "/var/task/requests/models.py", line 898, in json
     return complexjson.loads(self.text, **kwargs)
   File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads
     return _default_decoder.decode(s)
   File "/var/lang/lib/python3.7/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/var/lang/lib/python3.7/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by sblack4** [comment]
**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/serverless-aws-python3-fec-datasync-dev-FinancialSummaryLoader  
start-time: -3600s  
end-time: 0s  
query-string:
```
fields @timestamp, @message
| sort @timestamp desc
| filter @message like 'status_code'
```
-----------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                            @message                                             |
|-------------------------|-------------------------------------------------------------------------------------------------|
| 2020-09-22 15:41:09.205 | [DEBUG] 2020-09-22T15:41:09.205Z 1c2bdff4-d158-5b54-9544-8810cc702a67 Recieved status_code 429  |
| 2020-09-22 15:41:08.668 | [DEBUG] 2020-09-22T15:41:08.667Z 1c2bdff4-d158-5b54-9544-8810cc702a67 Recieved status_code 429  |
| 2020-09-22 15:25:44.215 | [DEBUG] 2020-09-22T15:25:44.214Z bf342f5f-c66b-5901-8f0c-78bbdf3302fd Recieved status_code 429  |
| 2020-09-22 15:25:43.667 | [DEBUG] 2020-09-22T15:25:43.667Z bf342f5f-c66b-5901-8f0c-78bbdf3302fd Recieved status_code 429  |
| 2020-09-22 15:25:29.684 | [DEBUG] 2020-09-22T15:25:29.684Z bf342f5f-c66b-5901-8f0c-78bbdf3302fd Recieved status_code 429  |
| 2020-09-22 15:24:45.005 | [DEBUG] 2020-09-22T15:24:45.5Z bf342f5f-c66b-5901-8f0c-78bbdf3302fd Recieved status_code 429    |
| 2020-09-22 15:24:12.582 | [DEBUG] 2020-09-22T15:24:12.581Z f227e266-5432-5ceb-a405-b5824d6af717 Recieved status_code 502  |
| 2020-09-22 15:24:11.759 | [DEBUG] 2020-09-22T15:24:11.759Z 2406da52-446e-57fd-a5a9-8db65d36aaa8 Recieved status_code 502  |
| 2020-09-22 15:24:11.611 | [DEBUG] 2020-09-22T15:24:11.611Z 4577b498-dee1-520c-9384-e37cc7c6f912 Recieved status_code 502  |
| 2020-09-22 15:19:33.632 | [DEBUG] 2020-09-22T15:19:33.632Z f93205eb-7db4-5a4b-a521-520f6a64484a Recieved status_code 429  |
| 2020-09-22 15:19:33.093 | [DEBUG] 2020-09-22T15:19:33.93Z f93205eb-7db4-5a4b-a521-520f6a64484a Recieved status_code 429   |
| 2020-09-22 15:16:14.888 | [DEBUG] 2020-09-22T15:16:14.888Z b1a171a5-2f12-5f21-ab28-26413824ad20 Recieved status_code 429  |
| 2020-09-22 15:14:29.859 | [DEBUG] 2020-09-22T15:14:29.859Z 8cfbd744-279d-507c-863c-80a0313b55f8 Recieved status_code 429  |
| 2020-09-22 15:13:09.709 | [DEBUG] 2020-09-22T15:13:09.709Z 8cfbd744-279d-507c-863c-80a0313b55f8 Recieved status_code 429  |
| 2020-09-22 15:13:07.666 | [DEBUG] 2020-09-22T15:13:07.666Z 8cfbd744-279d-507c-863c-80a0313b55f8 Recieved status_code 429  |
| 2020-09-22 15:13:07.131 | [DEBUG] 2020-09-22T15:13:07.131Z 8cfbd744-279d-507c-863c-80a0313b55f8 Recieved status_code 429  |
| 2020-09-22 15:08:58.214 | [DEBUG] 2020-09-22T15:08:58.214Z 015eace6-d689-5e7c-8ef4-fb02c3db8b69 Recieved status_code 429  |
| 2020-09-22 15:08:57.682 | [DEBUG] 2020-09-22T15:08:57.681Z 015eace6-d689-5e7c-8ef4-fb02c3db8b69 Recieved status_code 429  |
| 2020-09-22 15:01:30.011 | [DEBUG] 2020-09-22T15:01:30.10Z 06b437c7-995c-5f48-9d5a-60238a35d1aa Recieved status_code 429   |
| 2020-09-22 14:58:59.345 | [DEBUG] 2020-09-22T14:58:59.345Z 06b437c7-995c-5f48-9d5a-60238a35d1aa Recieved status_code 429  |
| 2020-09-22 14:58:57.259 | [DEBUG] 2020-09-22T14:58:57.259Z 06b437c7-995c-5f48-9d5a-60238a35d1aa Recieved status_code 429  |
| 2020-09-22 14:58:56.716 | [DEBUG] 2020-09-22T14:58:56.716Z 06b437c7-995c-5f48-9d5a-60238a35d1aa Recieved status_code 429  |
| 2020-09-22 14:50:59.739 | [DEBUG] 2020-09-22T14:50:59.738Z faf458f1-aa69-5ad4-afd6-0f15baeae654 Recieved status_code 429  |
-----------------------------------------------------------------------------------------------------------------------------


The 429s are expected. The 502s must be what is throwing the json decode error.

**Comment by sblack4** [comment]
I'm reopening this as it should be handled with a custom error message so as not to confuse
