### ISSUE TITLE
Some filings are larger than the lamba tmp space 

### ISSUE THREAD

**Issue by sblack4** [Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor#37]
```
[ERROR] OSError: [Errno 28] No space left on device Traceback (most recent call last):
   File "/var/task/src/FECFileLoader.py", line 128, in lambdaHandler
     json.dump(val, fh, default=serialize_dates)
   File "/var/lang/lib/python3.7/json/__init__.py", line 180, in dump
     fp.write(chunk)
```

**Comment by sblack4** [comment]
:rage1: to mount EFS the lambdas need to be in a VPC https://docs.aws.amazon.com/lambda/latest/dg/configuration-filesystem.html

**Comment by sblack4** [comment]
The other option that avoids this issue is writing directly to DynamoDB and then copying from there. 

some links:

- https://docs.aws.amazon.com/redshift/latest/dg/t_Loading-data-from-dynamodb.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html
- https://www.serverless.com/dynamodb
