### ISSUE TITLE
[bug] ProvisionedThroughputExceededException writing larger tables to dynamodb

### ISSUE THREAD

**Issue by sblack4** [Advertising-Analytics-LLC/serverless-aws-fec-data-collectionor#43]
```

[ERROR] ProvisionedThroughputExceededException: An error occurred (ProvisionedThroughputExceededException) when calling the BatchWriteItem operation (reached max retries: 9): The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.
Traceback (most recent call last):
  File "/var/task/src/FECFileLoader.py", line 141, in lambdaHandler
    Item=itm
  File "/var/task/boto3/dynamodb/table.py", line 101, in put_item
    self._add_request_and_process({'PutRequest': {'Item': Item}})
  File "/var/task/boto3/dynamodb/table.py", line 110, in _add_request_and_process
    self._flush_if_needed()
  File "/var/task/boto3/dynamodb/table.py", line 131, in _flush_if_needed
    self._flush()
  File "/var/task/boto3/dynamodb/table.py", line 137, in _flush
    RequestItems={self._table_name: items_to_send})
  File "/var/task/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)

```

**Comment by sblack4** [comment]
It was this chonk. (*ohh lawd he comin*)

```
INFO:  Load into table 'filings_schedule_b' completed, 3521 record(s) loaded successfully.
```
